### ISSUE TITLE
Legacy map file format support

### ISSUE THREAD

**Issue by johnbeech** [df-map-archive/dfma-html5-map-viewer#44]
See:
- https://mkv25.net/dfma/map-1184-laurion?viewer=html5

```
readers.js:86 RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at h.parse (parser.js:173:32)
    at i (readers.js:84:13)
    at async set-map-by-url.js:24:11
    at async r (setup-starting-map.js:6:9)
```

Map file:
- https://mkv25.net/dfma/maps-archived/local_map-6-1053-14365.fdf-map

**Comment by johnbeech** [comment]
I've replaced parcel with vite on the branch; to avoid obscure build errors. 

This seems to work well, but still seeing problems with the map loading:
```
readers.js:86 RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at MapData.parse (parser.js:173:32)
    at loadMapFromURL (readers.js:84:13)
    at async set-map-by-url.js:24:17
```

And the published `map-viewer.js` is now a module, so I'll have to bump to version 2.0.0 - and change how the DFMA website loads (Using `<script src="./map-viewer.js" type="module" />` locally)

**Comment by johnbeech** [comment]
https://github.com/df-map-archive/dfma-html5-map-viewer/pull/46
